### ISSUE TITLE
Angular2 food view not updating

### ISSUE THREAD

**Issue by cveld** [FabianGosebrink/ASPNETCore-Angular-SignalR-Typescript#9] opened 2016-06-30 09:59 UTC
When I add a new food item, the Angular2 view is not updating. I need to click on it first. I have tested in Chrome, IE11, Edge.

Using breakpoints in the c# code I see that the getallitems webapi call is being hit.
Using breakpoints in the javascript code I see that the stream is hit and that the json mapping towards an array takes place. The view model gets populated, i.e. the assignment `this.foodItems = data` in the file `foodcomponent.ts` takes place.

**Comment by FabianGosebrink** [comment] 2016-06-30 16:09
The food view updates once at my computer locally. The problem is that Signalr is really really shaky and not stable at all. So I think we have to wait here until something stable is out.

**Comment by cveld** [comment] 2016-07-01 08:18
you are really sure it's Signalr? I get breakpoint hits all the time:

![image](https://cloud.githubusercontent.com/assets/6196260/16515893/ffae7ce8-3f74-11e6-8e53-e158296b459e.png)

So I confirm the assignment always takes place. It is only that the view is not picking up updates on the array `foodItems`.

**Comment by FabianGosebrink** [comment] 2016-07-01 08:21
I did take a look into this and also saw that it might be a angular2-change-detection thing. I will have a look into this. ;)

**Comment by FabianGosebrink** [comment] 2016-07-01 20:58
used ngzone...so closing this for now.

**Closed as completed by FabianGosebrink** 2016-07-01 20:58 UTC
